name: Publish

on:
  create:
    tags:
      - v*
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest
    environment: Publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Checks
        run: |
          git config --global user.name "CI"
          ./mill __.checkFormat + __.test

      - name: SetupPGP
        run: |
          mkdir -p ~/.gnupg && chmod 700 ~/.gnupg
          echo "allow-preset-passphrase" >> ~/.gnupg/gpg-agent.conf
          gpgconf --kill gpg-agent
          echo "$ORG_SIGNING_KEY" | gpg --batch --import
          PASS_HEX=$(printf '%s' "$ORG_SIGNING_PASSWORD" | od -A n -t x1 | tr -d ' \n')
          for KEYGRIP in $(gpg --list-secret-keys --with-keygrip --with-colons | awk -F: '/^grp/{print $10}'); do
            gpg-connect-agent "PRESET_PASSPHRASE $KEYGRIP -1 $PASS_HEX" /bye
          done
        env:
          ORG_SIGNING_KEY: ${{ secrets.ORG_SIGNING_KEY }}
          ORG_SIGNING_PASSWORD: ${{ secrets.ORG_SIGNING_PASSWORD }}

      - name: Publish
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') || github.event_name == 'release'
        run: |
          git fetch --prune --unshallow
          ./mill mill.scalalib.SonatypeCentralPublishModule/ \
            --useGpgCli true \
            --gpgArgs "--no-tty,--pinentry-mode,loopback,--batch,--yes,--armor,--detach-sign"
        env:
          MILL_SONATYPE_USERNAME: ${{ secrets.ORG_SONATYPE_USERNAME }}
          MILL_SONATYPE_PASSWORD: ${{ secrets.ORG_SONATYPE_PASSWORD }}
